version: "3.8"

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./src:/var/www/html
        depends_on:
            - php
        networks:
            - camagru_net

    php:
        build:
            context: ./docker/php
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - camagru_net

    mariadb:
        container_name: mariadb
        build:
            context: ./docker/mariadb
        image: alaparic-mariadb
        env_file:
            - .env
        expose:
            - "3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - camagru_net
        restart: always

volumes:
    db_data:

networks:
    camagru_net:
        name: camagru_net
        driver: bridge
