version: "3.8"

services:
    web:
        image: nginx:latest
        container_name: nginx_container
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/var/www/html
        depends_on:
            - php
        networks:
            - camagru_net

    php:
        image: php:7.4-fpm
        container_name: php_container
        volumes:
            - ./src:/var/www/html
        networks:
            - camagru_net

    db:
        image: mariadb:10.5.8
        container_name: mysql_container
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - camagru_net

volumes:
    db_data:

networks:
    camagru_net:
        name: camagru_net
        driver: bridge
