services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../src:/var/www/html
        depends_on:
            - php
        networks:
            - camagru_net
        restart: always

    php:
        build:
            context: ./php
        container_name: php
        env_file:
            - ../.env
        volumes:
            - ../src:/var/www/html
        depends_on:
            - mariadb
        networks:
            - camagru_net
        restart: always

    mariadb:
        container_name: mariadb
        image: alaparic-mariadb
        build:
            context: ./mariadb
        env_file:
            - ../.env
        expose:
            - "3306"
        networks:
            - camagru_net
        restart: always

networks:
    camagru_net:
        name: camagru_net
        driver: bridge
