CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    emailCommentPreference BOOLEAN DEFAULT TRUE,
    emailConfirmed BOOLEAN DEFAULT FALSE
);

CREATE TABLE post (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    likes INT DEFAULT 0,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE postedImage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    postId INT NOT NULL,
    imagePath VARCHAR(255) NOT NULL,
    FOREIGN KEY (postId) REFERENCES post(id) ON DELETE CASCADE
);

CREATE TABLE comment (
    UniqueID INT AUTO_INCREMENT PRIMARY KEY,
    postId INT NOT NULL,
    commenterId INT NOT NULL,
    message TEXT NOT NULL,
    likes INT DEFAULT 0,
    FOREIGN KEY (postId) REFERENCES post(id) ON DELETE CASCADE,
    FOREIGN KEY (commenterId) REFERENCES user(id) ON DELETE CASCADE
);
